insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Rowe-Kunde", "marijuana", 994634, "dion.kunde@gmail.com", "green7", "332-767-2908 x393", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kuphal-Spinka", "marijuana", 652463, "wilhelmina.hermann@yahoo.com", "cyan8", "845-634-4786", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Christiansen-Wiegand", "marijuana", 136643, "refugio.gislason@yahoo.com", "grey6", "(520) 869-8955", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hagenes-Gislason", "marijuana", 634068, "candance.cummings@hotmail.com", "blue0", "437-110-6014 x322", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Davis-Hessel", "marijuana", 495816, "gladys.kuphal@yahoo.com", "lavender4", "423.868.0399 x965", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Reichel-Balistreri", "marijuana", 168090, "malvina.purdy@yahoo.com", "sky blue2", "644-480-0824 x764", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mills, Halvorson and Bode", "marijuana", 962928, "maynard.beer@gmail.com", "red5", "1-086-965-5153 x186", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Grady, Conroy and Tremblay", "marijuana", 729564, "joan.oberbrunner@hotmail.com", "violet5", "158.953.7063 x89011", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gutmann-Hoppe", "marijuana", 970952, "sparkle.wunsch@hotmail.com", "maroon5", "1-926-854-2590 x4997", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Rath, Schoen and Ankunding", "marijuana", 979391, "jamey.sauer@hotmail.com", "grey9", "(653) 771-2849 x5943", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Orn, Emmerich and Schumm", "marijuana", 112860, "deloise.romaguera@yahoo.com", "silver2", "(705) 634-0759 x3661", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bashirian-Wolf", "marijuana", 382046, "charley.collier@yahoo.com", "fuchsia6", "1-587-366-8696 x886", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Stanton LLC", "marijuana", 384187, "adelaida.ortiz@gmail.com", "sky blue4", "1-379-048-8409 x02561", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Grant Group", "marijuana", 625769, "darron.lockman@yahoo.com", "sky blue5", "481-062-6761", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kuhic Inc", "marijuana", 681663, "vern.robel@hotmail.com", "orchid1", "(493) 459-7450 x7906", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Shields-Ratke", "marijuana", 880517, "rich.bartoletti@yahoo.com", "blue3", "969.048.9969", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Rice-Stracke", "marijuana", 557339, "dorene.schneider@hotmail.com", "black4", "647-316-9911", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Jakubowski and Sons", "marijuana", 863060, "keena.russel@gmail.com", "black4", "816.082.4675", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Cassin, Gutkowski and Jones", "marijuana", 208260, "harley.murazik@yahoo.com", "pink6", "405-237-6940 x35234", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Greenholt Inc", "marijuana", 620639, "ashley.rohan@yahoo.com", "purple6", "1-003-097-7330", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lind-Corkery", "marijuana", 412939, "maria.satterfield@hotmail.com", "pink5", "168.574.7391 x2236", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Buckridge LLC", "marijuana", 395793, "oma.rutherford@hotmail.com", "sky blue9", "322.725.8219 x95537", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Trantow and Sons", "marijuana", 827534, "monserrate.morissette@hotmail.com", "grey3", "857.800.8535 x50667", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Walter, Johns and Farrell", "marijuana", 856382, "parker.moen@hotmail.com", "sky blue2", "313-381-0210 x5783", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Shields-Tremblay", "marijuana", 337732, "rickie.halvorson@gmail.com", "sky blue8", "043.898.6713", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Parisian-Reilly", "marijuana", 237727, "fanny.howell@yahoo.com", "green2", "(885) 317-8365", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Jenkins-Abshire", "marijuana", 733205, "johnathon.kirlin@yahoo.com", "green0", "061.696.8315 x076", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wolf-Torphy", "marijuana", 970566, "michel.welch@yahoo.com", "turquoise5", "611.444.5938 x751", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lesch-Durgan", "marijuana", 651520, "gordon.runolfsson@yahoo.com", "black0", "214-516-9895 x8476", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Simonis, Cronin and Rice", "marijuana", 222663, "levi.lind@yahoo.com", "red9", "150-308-3905 x059", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Boyer-Schoen", "marijuana", 369076, "billy.will@yahoo.com", "yellow1", "(058) 520-8304 x1754", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Herman-Botsford", "marijuana", 254653, "domingo.goldner@gmail.com", "lavender7", "1-093-380-3692 x661", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hane, Hessel and Wisozk", "marijuana", 295911, "tina.smitham@hotmail.com", "olive5", "519-239-0703 x092", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Marvin and Sons", "marijuana", 216427, "man.gutmann@yahoo.com", "pink2", "(483) 276-7050 x004", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Weimann Inc", "marijuana", 651641, "norris.mohr@yahoo.com", "red8", "(813) 165-1659", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Barton-McKenzie", "marijuana", 545930, "avery.kohler@yahoo.com", "lime0", "(372) 706-7733 x5752", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Waters Group", "marijuana", 865853, "hermina.kuhn@hotmail.com", "orange1", "463.880.5440 x029", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Sporer, Prosacco and Bernhard", "marijuana", 891460, "judson.kilback@hotmail.com", "olive4", "867-149-4339 x7522", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("McKenzie, McKenzie and Koepp", "marijuana", 522763, "karly.osinski@yahoo.com", "fuchsia9", "(300) 247-9974 x135", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Cartwright LLC", "marijuana", 731253, "donette.farrell@yahoo.com", "salmon4", "007-277-4746 x46789", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Langworth, Krajcik and Harvey", "marijuana", 744333, "cedric.collins@hotmail.com", "black1", "431-451-2161 x260", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Blanda and Sons", "marijuana", 886160, "jenice.koch@gmail.com", "lavender5", "338-069-1383", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mertz-Jast", "marijuana", 747351, "freddie.orn@gmail.com", "cyan0", "(840) 875-0180 x502", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Sanford-Parisian", "marijuana", 643993, "edison.predovic@yahoo.com", "lime7", "(007) 465-5055", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Ernser Inc", "marijuana", 503238, "wilhelmina.medhurst@hotmail.com", "plum1", "1-922-472-8850", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bernier-Fisher", "marijuana", 924876, "juliane.hartmann@yahoo.com", "white8", "(492) 496-2142 x5827", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lesch Inc", "marijuana", 696378, "ramonita.mosciski@gmail.com", "grey2", "395-046-4994 x178", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Friesen, Mante and Batz", "marijuana", 883146, "burl.prohaska@hotmail.com", "azure4", "585.371.5126 x54154", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Greenfelder, Kovacek and Jones", "marijuana", 692376, "buena.abbott@yahoo.com", "pink9", "111.823.7759", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kautzer, Kris and Fadel", "marijuana", 899437, "waltraud.trantow@hotmail.com", "red1", "927-257-1908 x7264", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schaden, Steuber and Stanton", "marijuana", 857465, "wanda.okon@hotmail.com", "grey0", "(004) 287-6113", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Konopelski-Hackett", "marijuana", 501376, "wyatt.dickens@hotmail.com", "silver6", "1-121-339-5167", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schaden, Cummerata and Cremin", "marijuana", 270412, "dominique.upton@yahoo.com", "purple8", "517-776-3620", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hayes, Walker and Altenwerth", "marijuana", 750810, "james.miller@yahoo.com", "mint green5", "847-860-1937", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mosciski Inc", "marijuana", 106004, "myron.satterfield@yahoo.com", "indigo4", "999-714-2807 x35055", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schowalter Group", "marijuana", 777210, "lowell.stamm@gmail.com", "lime8", "369-126-0903", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Collier Inc", "marijuana", 503821, "lorenzo.harber@gmail.com", "sky blue0", "(654) 295-1448 x80345", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Beahan, Pacocha and O\'Keefe", "marijuana", 666098, "cherrie.collier@gmail.com", "orange6", "625.502.1616 x53441", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kovacek, Rau and Beer", "marijuana", 480443, "basil.collier@gmail.com", "yellow5", "714-965-0845 x120", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Weimann, Walsh and Paucek", "marijuana", 750454, "chance.kuhic@yahoo.com", "purple7", "(103) 746-3669", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Marquardt LLC", "marijuana", 217650, "ramona.effertz@gmail.com", "silver5", "296.408.9034 x877", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Pfeffer LLC", "marijuana", 290562, "edelmira.kunze@yahoo.com", "violet3", "1-416-979-7783 x086", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Blanda, Towne and Borer", "marijuana", 119378, "yasmin.becker@yahoo.com", "turquoise2", "263.889.9821", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kling Group", "marijuana", 718359, "patty.hermann@yahoo.com", "pink8", "616.791.1633", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Pouros LLC", "marijuana", 966788, "rosaria.abshire@yahoo.com", "tan6", "722-276-7090 x2547", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Collins, Osinski and Fahey", "marijuana", 342098, "debrah.jast@gmail.com", "pink8", "(581) 541-7053 x355", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Rogahn, Ratke and Spinka", "marijuana", 803205, "karly.prosacco@hotmail.com", "white5", "348.628.0940 x7943", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Tillman-Cole", "marijuana", 774132, "clemencia.rice@yahoo.com", "violet0", "380-954-2752 x3023", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lakin, Oberbrunner and Bode", "marijuana", 409307, "loyce.wolff@yahoo.com", "cyan4", "1-279-238-3191 x438", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Johnston, Volkman and Maggio", "marijuana", 801282, "rosella.witting@hotmail.com", "red2", "201.522.0789 x92948", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bradtke, Stokes and Labadie", "marijuana", 640031, "lorrine.hoeger@hotmail.com", "orange8", "1-214-487-6834 x7703", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Champlin-Hettinger", "marijuana", 704637, "barb.crooks@gmail.com", "violet3", "(433) 960-0977 x6743", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("O\'Kon, Kassulke and O\'Hara", "marijuana", 241330, "mirian.will@yahoo.com", "pink6", "(508) 990-4459", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schulist-Roberts", "marijuana", 390541, "frida.hessel@yahoo.com", "indigo9", "(934) 910-6281 x43289", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Ward, Shields and Kulas", "marijuana", 918660, "deane.bartell@hotmail.com", "purple6", "1-188-723-4322 x3644", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Jakubowski LLC", "marijuana", 722651, "adolph.lebsack@gmail.com", "silver6", "962.158.7366 x88786", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("O\'Conner and Sons", "marijuana", 705107, "anderson.bernier@gmail.com", "indigo8", "862-689-6142", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Heller LLC", "marijuana", 644490, "malcom.nienow@gmail.com", "red8", "432-021-4718 x550", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Green Inc", "marijuana", 711398, "tyler.cummings@hotmail.com", "ivory1", "876-771-8239 x2189", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kihn, Kemmer and Streich", "marijuana", 412884, "dwayne.greenholt@gmail.com", "plum6", "642-272-6820", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mosciski Group", "marijuana", 901837, "monique.littel@yahoo.com", "grey5", "572.547.8521", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Streich-Romaguera", "marijuana", 596580, "cliff.schulist@hotmail.com", "purple7", "(208) 459-0367 x02781", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wehner Inc", "marijuana", 339876, "herminia.lubowitz@gmail.com", "orange0", "(372) 714-7270", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("O\'Reilly-DuBuque", "marijuana", 137448, "erna.baumbach@hotmail.com", "salmon8", "903.968.3535 x105", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Roberts Group", "marijuana", 381812, "eloy.abernathy@yahoo.com", "pink9", "797.128.6708", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Windler-Kiehn", "marijuana", 576162, "doloris.mckenzie@yahoo.com", "white0", "483.064.0874", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Klocko, Daniel and Abbott", "marijuana", 536539, "pamula.hagenes@yahoo.com", "white2", "975.834.9772 x81501", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Osinski LLC", "marijuana", 760758, "annamae.buckridge@gmail.com", "white6", "309-950-5602", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wisoky, Lang and Sporer", "marijuana", 352526, "patrick.cartwright@yahoo.com", "lime8", "823.970.1134", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kassulke-Torp", "marijuana", 979693, "quinn.wintheiser@yahoo.com", "fuchsia7", "502.682.8767 x4732", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hyatt, Rutherford and McDermott", "marijuana", 397181, "jeannine.farrell@hotmail.com", "gold4", "021.640.0055 x9863", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Macejkovic LLC", "marijuana", 208200, "madelaine.jakubowski@hotmail.com", "turquoise3", "572.179.1368 x45093", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Fadel and Sons", "marijuana", 825076, "raylene.stark@gmail.com", "teal5", "014-610-2756", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Moore, Flatley and Kshlerin", "marijuana", 748418, "zane.corkery@yahoo.com", "pink8", "1-689-663-3682 x038", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schiller, Mertz and Schinner", "marijuana", 450457, "frankie.howe@gmail.com", "cyan0", "931-778-7870 x32092", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Luettgen, Predovic and Conn", "marijuana", 505182, "christian.beatty@yahoo.com", "plum4", "(352) 661-2549 x5366", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wisozk-Armstrong", "marijuana", 483263, "zack.stehr@gmail.com", "mint green1", "1-029-395-2826 x9271", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Reilly, Farrell and Brekke", "marijuana", 354596, "nilsa.deckow@hotmail.com", "sky blue7", "1-602-180-7101 x6665", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bradtke-Bradtke", "marijuana", 566735, "letisha.kihn@hotmail.com", "salmon0", "1-861-779-9199 x7452", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Grower (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Leffler, Powlowski and Nikolaus", "marijuana", 410517, "rod.willms@gmail.com", "azure3", "(794) 245-4240", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mertz Inc", "marijuana", 353954, "alexandra.bednar@hotmail.com", "magenta9", "(241) 279-0170 x22347", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lemke, Langworth and Howe", "marijuana", 356845, "oscar.tremblay@gmail.com", "gold5", "815-069-6765", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Dietrich, Hettinger and Terry", "marijuana", 822475, "quinn.reinger@yahoo.com", "white8", "237.427.8865", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Stiedemann, Haley and Rutherford", "marijuana", 904551, "bettye.little@yahoo.com", "maroon0", "022.495.6111 x1698", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Macejkovic-Keebler", "marijuana", 823815, "darrick.miller@yahoo.com", "pink4", "(721) 158-2014 x70366", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Turner-Jast", "marijuana", 336741, "blossom.roberts@gmail.com", "azure4", "369.128.7615 x57427", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Murray, Douglas and Rolfson", "marijuana", 784171, "gene.klein@gmail.com", "green5", "(556) 214-2088 x310", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hickle-Feil", "marijuana", 114096, "royal.effertz@hotmail.com", "red2", "491.150.0770", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Frami-Hettinger", "marijuana", 339656, "errol.jenkins@hotmail.com", "black5", "484-739-5348 x32888", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Heaney, Hagenes and Rath", "marijuana", 452692, "joetta.mohr@hotmail.com", "pink8", "1-062-061-5495 x02446", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Willms LLC", "marijuana", 883740, "adrian.adams@hotmail.com", "sky blue2", "476-957-1144", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Nikolaus Group", "marijuana", 883552, "luigi.predovic@yahoo.com", "azure8", "136-351-5728", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lynch LLC", "marijuana", 960646, "arthur.terry@hotmail.com", "purple1", "1-568-108-9256", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wilkinson-Pollich", "marijuana", 365221, "herschel.smith@hotmail.com", "plum0", "834-244-7856 x639", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Dibbert-Rath", "marijuana", 427309, "huey.hoppe@yahoo.com", "lavender0", "(267) 013-2994 x19307", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Boehm, Schamberger and Romaguera", "marijuana", 799099, "enriqueta.walker@gmail.com", "mint green4", "313.177.1223", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Cummings-Cole", "marijuana", 117428, "vicky.frami@yahoo.com", "magenta5", "882-575-9232 x21661", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kunde Group", "marijuana", 392942, "sid.rodriguez@gmail.com", "black1", "1-044-843-6012 x76091", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Casper, Conn and Beahan", "marijuana", 854371, "lino.windler@gmail.com", "red6", "250-370-9473", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Schulist, Homenick and West", "marijuana", 490628, "andrea.roob@yahoo.com", "ivory7", "053-916-6676", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Corkery, Jacobs and McCullough", "marijuana", 841133, "karl.kunde@yahoo.com", "purple0", "615-292-1086", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gutkowski Inc", "marijuana", 485034, "leland.cronin@gmail.com", "teal1", "1-539-249-4368", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kautzer-Dickinson", "marijuana", 455195, "albertha.schumm@hotmail.com", "ivory7", "(833) 678-6520", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Witting-Kuhic", "marijuana", 998948, "carry.spinka@yahoo.com", "blue9", "1-534-227-2487 x649", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lebsack, Parisian and Abernathy", "marijuana", 783524, "tobias.kling@yahoo.com", "mint green8", "1-727-626-0114 x2509", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Collier Group", "marijuana", 360254, "iraida.torp@yahoo.com", "green7", "1-942-035-4672 x16769", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Rodriguez-Cassin", "marijuana", 859967, "desiree.balistreri@yahoo.com", "purple0", "1-258-585-2453", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Stark, Gislason and Pagac", "marijuana", 430668, "fatimah.nitzsche@yahoo.com", "lavender1", "(412) 608-6469", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gleason, Mueller and Kirlin", "marijuana", 591049, "jackie.hane@hotmail.com", "purple3", "1-816-207-9159 x17019", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mante-Hand", "marijuana", 517819, "leda.mills@yahoo.com", "fuchsia9", "993-290-6834", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Tremblay-Bogan", "marijuana", 462581, "marni.sporer@yahoo.com", "cyan1", "668-207-0131", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Cremin-Maggio", "marijuana", 820053, "hobert.mitchell@yahoo.com", "silver5", "371-110-3864 x2106", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bednar-Dickens", "marijuana", 460649, "kim.ebert@yahoo.com", "green9", "1-510-554-8937 x394", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kohler Group", "marijuana", 565700, "abe.rice@gmail.com", "black2", "1-134-895-3521", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Keebler-Heathcote", "marijuana", 310353, "lucius.hessel@gmail.com", "red5", "267.561.7763", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Nolan, Cole and Stracke", "marijuana", 589286, "lenna.rippin@yahoo.com", "white8", "620-281-3205", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gleichner and Sons", "marijuana", 367587, "troy.reinger@gmail.com", "cyan1", "660-578-9090", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Runolfsson, Mertz and Kirlin", "marijuana", 367339, "sammy.parker@hotmail.com", "orchid2", "114-371-3385 x1189", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Quigley, Dibbert and Yundt", "marijuana", 687428, "drew.smitham@hotmail.com", "magenta7", "197.244.5416 x269", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hills, Boyer and Lynch", "marijuana", 337750, "liz.pagac@gmail.com", "maroon1", "680-589-7028", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bauch-Johns", "marijuana", 935318, "shannon.rempel@yahoo.com", "indigo5", "1-434-610-0935 x067", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lakin, Jast and Price", "marijuana", 876905, "junko.anderson@yahoo.com", "azure5", "(144) 768-8026 x54481", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Stroman-Price", "marijuana", 715685, "miguel.schiller@gmail.com", "green1", "929.415.8003", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Padberg-Lebsack", "marijuana", 802450, "jesusita.reilly@gmail.com", "green1", "1-371-221-7922", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Braun-Hauck", "marijuana", 831205, "natalya.stark@hotmail.com", "fuchsia7", "412.744.3046", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Nitzsche, Senger and White", "marijuana", 857344, "tim.lemke@gmail.com", "azure3", "953.921.7622", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Senger-Metz", "marijuana", 593510, "clay.barton@gmail.com", "orange6", "(720) 465-5453 x471", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gorczany and Sons", "marijuana", 551390, "fred.altenwerth@gmail.com", "mint green1", "720-339-5731", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gottlieb-Mertz", "marijuana", 864025, "parthenia.hoeger@gmail.com", "yellow2", "754.501.8363 x7769", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mueller Inc", "marijuana", 578273, "jordon.schuster@hotmail.com", "magenta7", "919.814.9787 x60107", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Jacobson Group", "marijuana", 951152, "josephina.padberg@gmail.com", "grey2", "(626) 775-2804", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kuhlman-Sanford", "marijuana", 948512, "emerson.wilderman@hotmail.com", "gold6", "1-478-316-5701 x8568", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Tillman, Collins and Gusikowski", "marijuana", 542594, "brianna.kessler@hotmail.com", "fuchsia7", "491.488.5677", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Lebsack and Sons", "marijuana", 451286, "vince.pollich@yahoo.com", "white1", "682.023.1172 x5786", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Mueller-Hudson", "marijuana", 255451, "lavada.von@yahoo.com", "tan1", "1-376-714-1337", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Moore, West and Runolfsson", "marijuana", 234381, "hoyt.bernhard@gmail.com", "lime4", "(310) 965-3681", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("DuBuque-Nolan", "marijuana", 657754, "stefania.ratke@gmail.com", "lavender7", "584.832.8242", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wolff, Mante and Hartmann", "marijuana", 257722, "noe.conroy@hotmail.com", "pink0", "929.577.3614 x49904", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Romaguera, Leffler and Wiza", "marijuana", 197319, "rudy.marvin@yahoo.com", "purple6", "(579) 038-0465", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Swaniawski Group", "marijuana", 141793, "isreal.considine@yahoo.com", "gold0", "(830) 959-8232", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hammes-Franecki", "marijuana", 509602, "mauro.kozey@hotmail.com", "orchid0", "(850) 644-3744", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Volkman-Skiles", "marijuana", 832599, "burl.marvin@yahoo.com", "violet1", "669.048.5528 x06643", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Armstrong Inc", "marijuana", 669094, "esta.adams@gmail.com", "white9", "092.901.7010 x5294", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Walker Group", "marijuana", 649165, "jenice.ruecker@hotmail.com", "fuchsia0", "869.862.8918 x10759", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Gutmann Inc", "marijuana", 230113, "tina.swaniawski@gmail.com", "pink2", "083-149-8079 x3288", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("O\'Reilly-Langworth", "marijuana", 973751, "carolina.bartell@hotmail.com", "teal1", "(120) 546-4458", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Feest Group", "marijuana", 335778, "kyra.harvey@hotmail.com", "blue2", "532-083-6061 x433", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hilpert and Sons", "marijuana", 189244, "racheal.kessler@gmail.com", "violet3", "(175) 625-5483 x804", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kutch Inc", "marijuana", 348834, "owen.donnelly@hotmail.com", "purple9", "934-963-6936 x28970", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hirthe, Lemke and Von", "marijuana", 797250, "domingo.lynch@yahoo.com", "lavender8", "229-137-6208 x82572", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Murray, Jakubowski and Simonis", "marijuana", 301459, "nettie.hintz@yahoo.com", "lavender2", "055.166.8020", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Champlin Group", "marijuana", 404767, "joel.prohaska@yahoo.com", "cyan4", "(694) 161-6657 x450", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Powlowski Group", "marijuana", 353175, "everette.king@gmail.com", "purple8", "941.307.4822", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hauck and Sons", "marijuana", 456302, "marjorie.mcdermott@hotmail.com", "fuchsia9", "1-856-615-5160", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Ferry-Purdy", "marijuana", 383336, "kurtis.kris@yahoo.com", "yellow3", "871.998.4827 x2135", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Friesen-Frami", "marijuana", 597126, "jonelle.smitham@yahoo.com", "plum7", "697-152-8775 x1161", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Denesik and Sons", "marijuana", 509992, "jonas.jast@hotmail.com", "fuchsia8", "356-655-9963 x952", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Pacocha LLC", "marijuana", 318614, "numbers.kuvalis@yahoo.com", "silver4", "062.863.8669 x1814", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Reilly, Williamson and Howell", "marijuana", 821610, "virgilio.heaney@gmail.com", "lime7", "274.408.9270 x557", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wisoky Inc", "marijuana", 679065, "ernesto.weber@yahoo.com", "blue1", "702-699-7970 x87163", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Morissette Group", "marijuana", 577876, "nannette.emmerich@yahoo.com", "blue5", "1-476-886-8307 x4450", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kub and Sons", "marijuana", 680940, "raymundo.nicolas@hotmail.com", "salmon5", "1-373-677-6893 x681", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Bernhard, Dietrich and Kohler", "marijuana", 974065, "hattie.roob@hotmail.com", "lavender8", "1-901-369-1196 x9211", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Tremblay Inc", "marijuana", 370556, "bulah.huels@yahoo.com", "orange2", "003.936.9573", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Jast-Kertzmann", "marijuana", 613206, "jefferey.ernser@hotmail.com", "magenta1", "759-252-1188", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Medhurst Inc", "marijuana", 111783, "daniela.hoppe@hotmail.com", "gold2", "325.453.4231 x5955", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Feeney, Pfannerstill and Ritchie", "marijuana", 697545, "bryanna.vonrueden@yahoo.com", "cyan0", "(512) 858-8967 x56027", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hoppe-Schaden", "marijuana", 258328, "chuck.halvorson@gmail.com", "red0", "1-229-396-8067 x622", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wilkinson, Jones and Hoppe", "marijuana", 110327, "andreas.jacobson@yahoo.com", "teal8", "1-686-608-8003 x526", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Hammes-Yundt", "marijuana", 737277, "isabelle.bechtelar@yahoo.com", "purple2", "218.696.2790", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("DuBuque-Sporer", "marijuana", 134047, "erma.pfeffer@yahoo.com", "cyan8", "353-746-4770 x804", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Thompson, Reynolds and Gibson", "marijuana", 521251, "stanley.moen@hotmail.com", "cyan7", "(250) 463-2013 x2057", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Monahan-Halvorson", "marijuana", 129369, "tracey.lesch@hotmail.com", "olive3", "(968) 369-1084 x088", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Grady Inc", "marijuana", 702704, "monique.huels@gmail.com", "teal1", "000-485-5454", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Wisozk and Sons", "marijuana", 812323, "delbert.hoppe@hotmail.com", "grey2", "(493) 505-8332", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Kemmer-Swaniawski", "marijuana", 468378, "ursula.nikolaus@gmail.com", "cyan0", "675.937.2283", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Turner and Sons", "marijuana", 963877, "tamera.okon@gmail.com", "teal9", "704-602-4691 x28741", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Haag, Goyette and Erdman", "marijuana", 344843, "jaqueline.schmitt@gmail.com", "orange6", "1-689-501-5758 x289", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Zemlak, Breitenberg and Fay", "marijuana", 821942, "kassandra.ferry@hotmail.com", "cyan4", "691.861.7275 x0534", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Distributor (name, businessType, licenseNumber, email, password, phoneNumber, description, imageURL) values ("Stehr and Sons", "marijuana", 358204, "chet.harris@gmail.com", "cyan6", "1-938-524-5517", "we sell weed", "https://imgur.com/gallery/5AjlRhE");
insert into Product (growerId, name, price, quantity, description, imageURL) values (21, "Minny van Gogh", 56.20, 32679, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (67, "Alf A. Romeo", 133.30, 15293, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (27, "Al B. Tross", 133.30, 37278, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (2, "Carrie A. Tune", 19.20, 84525, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (69, "Shanda Lear", 108.10, 30683, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (3, "Phil Graves", 82.70, 77158, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (13, "Rex Easley", 94.20, 27694, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (9, "Dusty Rhodes", 20.80, 50715, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (50, "Homan Provement", 89.70, 44255, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (63, "Myra Maines", 128.20, 37847, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (17, "Mark A. Roni", 106.40, 90463, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (13, "Allen Rench", 67.10, 82388, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (53, "Gus Tofwin", 68.60, 2452, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (38, "Mary Ann Bright", 50.00, 1584, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (27, "Pearl E. Gates", 44.80, 10203, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (20, "Andy Structible", 142.10, 94372, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (3, "Milly Graham", 60.40, 88086, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (50, "Di O\'Bolic", 103.80, 15848, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (15, "Eve Ning", 138.40, 67140, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (34, "Jim Shorts", 34.90, 39617, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (14, "Rich Mann", 116.20, 1314, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (69, "Lily Pond", 77.30, 93749, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (55, "Ferris Wheeler", 89.70, 76364, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (22, "Olive Branch", 116.10, 56315, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (1, "Kenney C. Strait", 67.10, 82665, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (85, "Carrie Oakey", 125.20, 56747, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (81, "Penny Nichols", 107.60, 23403, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (31, "Sam Pull", 135.70, 6777, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (57, "Candice B. DePlace", 56.20, 32189, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (12, "Carlotta Tendant", 19.80, 82459, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (26, "Kurt Remarque", 50.50, 58545, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (1, "Manuel Labor", 104.60, 2757, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (71, "Tim Burr", 17.70, 57770, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (5, "Barry Shmelly", 125.10, 32992, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (3, "Nick Ovtime", 80.80, 42406, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (47, "Minny van Gogh", 61.80, 10160, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (37, "Lou Briccant", 71.70, 22955, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (69, "Des Buratto", 15.10, 42773, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (7, "Buddy System", 73.40, 85209, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (46, "Luna Tick", 85.20, 55876, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (58, "Mel Function", 118.80, 54758, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (58, "Ariel Hassle", 22.60, 40705, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (21, "Sue Render", 127.50, 53662, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (53, "Jim Sox", 100.90, 16551, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (77, "Joanna Hand", 54.90, 60311, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (25, "Rocky Rhoades", 67.30, 21522, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (59, "Kerry Oki", 110.10, 17678, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (58, "R. M. Pitt", 96.70, 51458, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (32, "Cole Kutz", 73.80, 61039, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (79, "Yule B. Sari", 68.60, 45014, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (67, "Jasmine Rice", 17.50, 16542, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (12, "Lily Pond", 47.00, 41559, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (52, "Kenya Dewit", 76.60, 63017, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (6, "Lisa Carr", 80.30, 18401, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (12, "Ellie Noise", 95.00, 15937, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (28, "Emerald Stone", 115.70, 11897, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (44, "Anita Bathe", 130.50, 81138, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (36, "Harrison Fire", 92.60, 49171, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (38, "Kristie Hannity", 24.20, 48565, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (50, "Mary Ott", 102.70, 45462, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (12, "Mike Rohsopht", 58.90, 27185, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (26, "Rhea Pollster", 129.70, 20888, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (10, "Rick Shaw", 29.30, 39598, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (16, "Jack Hammer", 85.80, 34505, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (77, "Justin Credible", 102.60, 69366, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (22, "Nick O\'Teen", 70.50, 11673, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (59, "Earl Lee Riser", 50.60, 27212, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (7, "Lon Moore", 41.90, 38268, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (28, "Hope Ferterbest", 126.20, 61286, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (83, "Roman Holiday", 28.10, 73529, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (46, "Ginger Rayl", 62.50, 981, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (62, "Juan De Hattatime", 136.70, 47329, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (47, "Perry Mecium", 125.40, 10118, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (88, "Anna Prentice", 126.50, 72952, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (53, "Kat Toy", 81.30, 70734, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (65, "Elmer Sklue", 16.90, 87219, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (80, "Sy Burnette", 103.50, 3028, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (7, "Sam Dayoulpay", 120.30, 70735, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (5, "Rowan Boatman", 55.30, 48634, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (36, "Rex Easley", 71.10, 10983, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (51, "Harry Legg", 109.80, 62461, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (63, "Curt N. Rodd", 115.60, 9271, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (47, "Douglas Furr", 92.20, 16205, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (31, "Crystal Claire Waters", 49.10, 75529, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (15, "Chi Spurger", 104.30, 40785, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (28, "Bea Minor", 56.50, 18987, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (24, "Doug Hole", 133.20, 62443, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (33, "Candice B. Fureal", 64.10, 27415, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (34, "Annie Moore", 116.30, 74197, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (78, "Ima Klotz", 143.60, 81365, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (39, "Carrie A. Tune", 99.20, 22692, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (42, "Winsom Cash", 133.30, 95180, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (45, "Hugo First", 94.20, 94041, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (32, "Diane Toluvia", 92.30, 12445, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (84, "Alf Abet", 80.90, 35346, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (19, "Aaron Thetires", 82.20, 25904, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (42, "Al Kaholic", 15.30, 27888, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (52, "Winnie Bago", 142.80, 38039, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (54, "Al O\'Moaney", 105.40, 52638, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into Product (growerId, name, price, quantity, description, imageURL) values (12, "Lowden Clear", 20.40, 74576, "the good stuff", "https://imgur.com/gallery/JgtdT");
insert into ProductReview (productId, reviewerId, rating, content) values (32, 18, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (19, 89, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (17, 87, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (4, 31, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (19, 11, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (36, 79, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (36, 22, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (56, 61, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (67, 29, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (13, 15, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (80, 84, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (67, 68, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (27, 21, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (77, 77, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (6, 66, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (49, 84, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (49, 17, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (61, 17, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (53, 57, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (2, 22, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (38, 43, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (63, 88, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (26, 88, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (2, 8, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (73, 81, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (74, 47, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (87, 46, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (67, 38, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (39, 18, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (67, 58, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (14, 26, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (16, 3, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (37, 78, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (27, 38, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (8, 54, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (21, 48, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (5, 70, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (75, 33, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (25, 89, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (24, 88, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (47, 22, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (68, 54, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (44, 69, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (29, 54, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (29, 15, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (6, 24, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (90, 51, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (64, 48, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (40, 15, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (14, 45, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (15, 78, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (48, 55, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (89, 23, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (85, 8, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (13, 54, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (78, 29, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (84, 58, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (55, 48, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (46, 13, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (24, 52, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (88, 12, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (67, 11, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (42, 71, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (6, 63, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (46, 23, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (79, 87, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (48, 6, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (9, 20, 1, "awful");
insert into ProductReview (productId, reviewerId, rating, content) values (61, 7, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (24, 36, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (59, 85, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (56, 41, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (21, 72, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (80, 64, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (2, 65, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (70, 50, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (47, 21, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (21, 57, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (85, 54, 3, "okay");
insert into ProductReview (productId, reviewerId, rating, content) values (79, 9, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (71, 19, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (21, 80, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (66, 51, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (80, 76, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (83, 19, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (6, 29, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (31, 34, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (33, 17, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (12, 55, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (19, 68, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (76, 83, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (56, 9, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (27, 46, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (8, 81, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (28, 76, 5, "good");
insert into ProductReview (productId, reviewerId, rating, content) values (16, 50, 4, "decent");
insert into ProductReview (productId, reviewerId, rating, content) values (27, 53, 2, "bad");
insert into ProductReview (productId, reviewerId, rating, content) values (83, 15, 3, "okay");
insert into Tag (value) values ("green");
insert into Tag (value) values ("brown");
insert into Tag (value) values ("smelly");
insert into Tag (value) values ("sweet");
insert into Tag (value) values ("cheap");
insert into Tag (value) values ("fancy");
insert into TagOwnership (tagId, productId) values (4, 1);
insert into TagOwnership (tagId, productId) values (1, 1);
insert into TagOwnership (tagId, productId) values (2, 2);
insert into TagOwnership (tagId, productId) values (5, 3);
insert into TagOwnership (tagId, productId) values (1, 3);
insert into TagOwnership (tagId, productId) values (2, 4);
insert into TagOwnership (tagId, productId) values (5, 5);
insert into TagOwnership (tagId, productId) values (2, 5);
insert into TagOwnership (tagId, productId) values (5, 6);
insert into TagOwnership (tagId, productId) values (4, 6);
insert into TagOwnership (tagId, productId) values (2, 6);
insert into TagOwnership (tagId, productId) values (1, 6);
insert into TagOwnership (tagId, productId) values (1, 7);
insert into TagOwnership (tagId, productId) values (2, 8);
insert into TagOwnership (tagId, productId) values (5, 8);
insert into TagOwnership (tagId, productId) values (5, 9);
insert into TagOwnership (tagId, productId) values (1, 9);
insert into TagOwnership (tagId, productId) values (4, 11);
insert into TagOwnership (tagId, productId) values (1, 11);
insert into TagOwnership (tagId, productId) values (4, 12);
insert into TagOwnership (tagId, productId) values (2, 13);
insert into TagOwnership (tagId, productId) values (4, 14);
insert into TagOwnership (tagId, productId) values (1, 14);
insert into TagOwnership (tagId, productId) values (3, 15);
insert into TagOwnership (tagId, productId) values (4, 15);
insert into TagOwnership (tagId, productId) values (5, 16);
insert into TagOwnership (tagId, productId) values (2, 16);
insert into TagOwnership (tagId, productId) values (3, 17);
insert into TagOwnership (tagId, productId) values (1, 17);
insert into TagOwnership (tagId, productId) values (5, 17);
insert into TagOwnership (tagId, productId) values (4, 18);
insert into TagOwnership (tagId, productId) values (4, 19);
insert into TagOwnership (tagId, productId) values (1, 19);
insert into TagOwnership (tagId, productId) values (3, 19);
insert into TagOwnership (tagId, productId) values (2, 20);
insert into TagOwnership (tagId, productId) values (4, 21);
insert into TagOwnership (tagId, productId) values (2, 21);
insert into TagOwnership (tagId, productId) values (4, 22);
insert into TagOwnership (tagId, productId) values (4, 23);
insert into TagOwnership (tagId, productId) values (5, 24);
insert into TagOwnership (tagId, productId) values (2, 25);
insert into TagOwnership (tagId, productId) values (5, 26);
insert into TagOwnership (tagId, productId) values (1, 27);
insert into TagOwnership (tagId, productId) values (2, 27);
insert into TagOwnership (tagId, productId) values (5, 27);
insert into TagOwnership (tagId, productId) values (3, 27);
insert into TagOwnership (tagId, productId) values (5, 28);
insert into TagOwnership (tagId, productId) values (4, 29);
insert into TagOwnership (tagId, productId) values (3, 29);
insert into TagOwnership (tagId, productId) values (2, 29);
insert into TagOwnership (tagId, productId) values (2, 30);
insert into TagOwnership (tagId, productId) values (5, 30);
insert into TagOwnership (tagId, productId) values (4, 31);
insert into TagOwnership (tagId, productId) values (5, 31);
insert into TagOwnership (tagId, productId) values (3, 31);
insert into TagOwnership (tagId, productId) values (2, 32);
insert into TagOwnership (tagId, productId) values (4, 32);
insert into TagOwnership (tagId, productId) values (1, 32);
insert into TagOwnership (tagId, productId) values (4, 33);
insert into TagOwnership (tagId, productId) values (2, 33);
insert into TagOwnership (tagId, productId) values (3, 33);
insert into TagOwnership (tagId, productId) values (5, 33);
insert into TagOwnership (tagId, productId) values (4, 34);
insert into TagOwnership (tagId, productId) values (2, 34);
insert into TagOwnership (tagId, productId) values (1, 34);
insert into TagOwnership (tagId, productId) values (5, 35);
insert into TagOwnership (tagId, productId) values (3, 35);
insert into TagOwnership (tagId, productId) values (5, 36);
insert into TagOwnership (tagId, productId) values (4, 37);
insert into TagOwnership (tagId, productId) values (3, 38);
insert into TagOwnership (tagId, productId) values (4, 38);
insert into TagOwnership (tagId, productId) values (3, 39);
insert into TagOwnership (tagId, productId) values (4, 39);
insert into TagOwnership (tagId, productId) values (1, 39);
insert into TagOwnership (tagId, productId) values (1, 40);
insert into TagOwnership (tagId, productId) values (2, 41);
insert into TagOwnership (tagId, productId) values (5, 41);
insert into TagOwnership (tagId, productId) values (2, 42);
insert into TagOwnership (tagId, productId) values (3, 45);
insert into TagOwnership (tagId, productId) values (2, 46);
insert into TagOwnership (tagId, productId) values (3, 47);
insert into TagOwnership (tagId, productId) values (2, 49);
insert into TagOwnership (tagId, productId) values (3, 49);
insert into TagOwnership (tagId, productId) values (4, 50);
insert into TagOwnership (tagId, productId) values (2, 50);
insert into TagOwnership (tagId, productId) values (2, 51);
insert into TagOwnership (tagId, productId) values (4, 51);
insert into TagOwnership (tagId, productId) values (3, 51);
insert into TagOwnership (tagId, productId) values (1, 52);
insert into TagOwnership (tagId, productId) values (2, 52);
insert into TagOwnership (tagId, productId) values (4, 52);
insert into TagOwnership (tagId, productId) values (2, 53);
insert into TagOwnership (tagId, productId) values (4, 53);
insert into TagOwnership (tagId, productId) values (1, 53);
insert into TagOwnership (tagId, productId) values (4, 54);
insert into TagOwnership (tagId, productId) values (3, 54);
insert into TagOwnership (tagId, productId) values (2, 54);
insert into TagOwnership (tagId, productId) values (4, 55);
insert into TagOwnership (tagId, productId) values (5, 55);
insert into TagOwnership (tagId, productId) values (3, 55);
insert into TagOwnership (tagId, productId) values (1, 56);
insert into TagOwnership (tagId, productId) values (2, 56);
insert into TagOwnership (tagId, productId) values (3, 57);
insert into TagOwnership (tagId, productId) values (4, 58);
insert into TagOwnership (tagId, productId) values (2, 58);
insert into TagOwnership (tagId, productId) values (4, 59);
insert into TagOwnership (tagId, productId) values (2, 59);
insert into TagOwnership (tagId, productId) values (3, 60);
insert into TagOwnership (tagId, productId) values (2, 61);
insert into TagOwnership (tagId, productId) values (4, 62);
insert into TagOwnership (tagId, productId) values (1, 62);
insert into TagOwnership (tagId, productId) values (3, 62);
insert into TagOwnership (tagId, productId) values (5, 62);
insert into TagOwnership (tagId, productId) values (4, 63);
insert into TagOwnership (tagId, productId) values (3, 63);
insert into TagOwnership (tagId, productId) values (1, 63);
insert into TagOwnership (tagId, productId) values (5, 64);
insert into TagOwnership (tagId, productId) values (2, 64);
insert into TagOwnership (tagId, productId) values (3, 64);
insert into TagOwnership (tagId, productId) values (4, 64);
insert into TagOwnership (tagId, productId) values (4, 65);
insert into TagOwnership (tagId, productId) values (1, 66);
insert into TagOwnership (tagId, productId) values (2, 66);
insert into TagOwnership (tagId, productId) values (5, 66);
insert into TagOwnership (tagId, productId) values (5, 67);
insert into TagOwnership (tagId, productId) values (4, 67);
insert into TagOwnership (tagId, productId) values (3, 68);
insert into TagOwnership (tagId, productId) values (2, 69);
insert into TagOwnership (tagId, productId) values (4, 69);
insert into TagOwnership (tagId, productId) values (3, 71);
insert into TagOwnership (tagId, productId) values (4, 71);
insert into TagOwnership (tagId, productId) values (5, 71);
insert into TagOwnership (tagId, productId) values (2, 71);
insert into TagOwnership (tagId, productId) values (2, 72);
insert into TagOwnership (tagId, productId) values (3, 72);
insert into TagOwnership (tagId, productId) values (4, 72);
insert into TagOwnership (tagId, productId) values (4, 73);
insert into TagOwnership (tagId, productId) values (3, 73);
insert into TagOwnership (tagId, productId) values (5, 74);
insert into TagOwnership (tagId, productId) values (2, 74);
insert into TagOwnership (tagId, productId) values (3, 74);
insert into TagOwnership (tagId, productId) values (1, 75);
insert into TagOwnership (tagId, productId) values (3, 75);
insert into TagOwnership (tagId, productId) values (1, 76);
insert into TagOwnership (tagId, productId) values (4, 77);
insert into TagOwnership (tagId, productId) values (5, 77);
insert into TagOwnership (tagId, productId) values (3, 78);
insert into TagOwnership (tagId, productId) values (5, 78);
insert into TagOwnership (tagId, productId) values (1, 78);
insert into TagOwnership (tagId, productId) values (4, 79);
insert into TagOwnership (tagId, productId) values (1, 79);
insert into TagOwnership (tagId, productId) values (2, 79);
insert into TagOwnership (tagId, productId) values (1, 80);
insert into TagOwnership (tagId, productId) values (2, 80);
insert into TagOwnership (tagId, productId) values (3, 80);
insert into TagOwnership (tagId, productId) values (2, 81);
insert into TagOwnership (tagId, productId) values (1, 81);
insert into TagOwnership (tagId, productId) values (5, 81);
insert into TagOwnership (tagId, productId) values (5, 82);
insert into TagOwnership (tagId, productId) values (2, 82);
insert into TagOwnership (tagId, productId) values (4, 82);
insert into TagOwnership (tagId, productId) values (1, 83);
insert into TagOwnership (tagId, productId) values (5, 84);
insert into TagOwnership (tagId, productId) values (3, 85);
insert into TagOwnership (tagId, productId) values (2, 85);
insert into TagOwnership (tagId, productId) values (5, 86);
insert into TagOwnership (tagId, productId) values (3, 86);
insert into TagOwnership (tagId, productId) values (4, 86);
insert into TagOwnership (tagId, productId) values (2, 86);
insert into TagOwnership (tagId, productId) values (5, 87);
insert into TagOwnership (tagId, productId) values (4, 87);
insert into TagOwnership (tagId, productId) values (3, 87);
insert into TagOwnership (tagId, productId) values (4, 89);
insert into TagOwnership (tagId, productId) values (3, 89);
insert into TagOwnership (tagId, productId) values (5, 90);
insert into TagOwnership (tagId, productId) values (4, 90);
insert into TagOwnership (tagId, productId) values (3, 91);
insert into TagOwnership (tagId, productId) values (5, 91);
insert into TagOwnership (tagId, productId) values (1, 91);
insert into TagOwnership (tagId, productId) values (2, 92);
insert into TagOwnership (tagId, productId) values (5, 93);
insert into TagOwnership (tagId, productId) values (3, 94);
insert into TagOwnership (tagId, productId) values (2, 94);
insert into TagOwnership (tagId, productId) values (5, 95);
insert into TagOwnership (tagId, productId) values (2, 96);
insert into TagOwnership (tagId, productId) values (5, 96);
insert into TagOwnership (tagId, productId) values (1, 96);
insert into TagOwnership (tagId, productId) values (5, 97);
insert into TagOwnership (tagId, productId) values (3, 97);
insert into TagOwnership (tagId, productId) values (2, 97);
insert into TagOwnership (tagId, productId) values (5, 98);
insert into TagOwnership (tagId, productId) values (2, 99);
insert into TagOwnership (tagId, productId) values (5, 99);
insert into TagOwnership (tagId, productId) values (1, 99);
insert into TagOwnership (tagId, productId) values (3, 99);
insert into TagOwnership (tagId, productId) values (5, 100);
insert into TagOwnership (tagId, productId) values (2, 100);
insert into TagOwnership (tagId, productId) values (3, 100);
